### ISSUE TITLE
Minnesota has a new flag

### ISSUE THREAD

**Issue by jessegavin** [lynnandtonic/usflags.design#24]
It will become official on May 11, 2024

https://en.wikipedia.org/wiki/Flag_of_Minnesota#2023_redesign_commission

![New Minnesota Flag](https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Minnesota_%282023_redesign%29.svg/2880px-Flag_of_Minnesota_%282023_redesign%29.svg.png)

**Comment by lynnandtonic** [comment]
It’s up! https://usflags.design/minnesota/

Thanks so much @jessegavin!
